baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Robotic Sea Bass'

theme = 'clarity'
introDescription = "Learn about Robotics, Software, and AI."
copyright = "Sebastian Castro"

[params.meta]
favicon = true
